name: integration

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: integration-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1

jobs:
  pebble:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-make
        run: cargo install cargo-make
      - name: Run integration tests
        run: cargo make test
